/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./components/Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Acme",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout(props: Props) {
  const { children } = props;

  return (
    <html lang="en">
      <head>
        <script
          type="importmap"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(
              {
                imports: {
                  react: "https://esm.sh/stable/react@18.2.0/es2022/react.mjs",
                  "react-dom":
                    "https://esm.sh/v135/react-dom@18.2.0/es2022/react-dom.bundle.mjs",
                  "react/jsx-runtime":
                    "https://esm.sh/stable/react@18.2.0/es2022/jsx-runtime.mjs",
                  "@acme/acme-product-catalog": toSpaUrl(
                    "acme-product-catalog"
                  ),
                  "@acme/acme-clients": toSpaUrl("acme-clients"),
                },
              },
              undefined,
              2
            ),
          }}
        ></script>
        <script src="https://cdn.jsdelivr.net/npm/es-module-shims@1.9.0/dist/es-module-shims.min.js" />
        <script
          src="https://esm.sh/stable/react@18.2.0/es2022/react.mjs"
          type="module"
        />
        <script
          src="https://esm.sh/v135/react-dom@18.2.0/es2022/react-dom.bundle.mjs"
          type="module"
        />
        <script
          src="https://esm.sh/stable/react@18.2.0/es2022/jsx-runtime.mjs"
          type="module"
        />
      </head>
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}

function toSpaUrl(ufront: string) {
  const spaPath =
    process.env.NODE_ENV == "development" ? "src/spa.tsx" : "spa.js";

  return `/ufronts/${ufront}/${spaPath}`;
}
